### ISSUE TITLE
the_code_of_training_code

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [xialeiliu/CrowdCounting_cvpr18#2]
Thanks for your nice job!@xialeiliu
I did not find the training code, could you please tell me how to train the model and reproduce the results of your paper?
Thanks for your reply!

**Comment by xialeiliu** [comment]
Thanks for you interest. Currently we are working on a technology
transferring project with the source code. We will try to release it as
soon as possible.

**Comment by priyanka-chaudhary** [comment]
Hello @xialeiliu : Any updates on when the training code would be released?
Thank you!
