### ISSUE TITLE
what is the ranking picture label?

### ISSUE THREAD

**Issue by xwjBupt** [xialeiliu/CrowdCounting_cvpr18#5]
hi,i have a few question.
1)what is the ranking picture label?is the ranking level?like 1,2,3?represents the size of the croped picture?
2)in Fig3,when the N=1,what is the 1*1(N*1)in the bule network lasts parts mean?the number of the ranking picture?or hat_Ci?
3)in the paper,you said that 
> In practice we sample minibatches of 25 images which contain 5 sets of 5 images which can be compared among them resulting in a total of 5 × (4 + 3 + 2 + 1) = 50 pairs in one minibatch.

what is the (4+3+2+1) mean?

thank you so much!!

**Comment by xialeiliu** [comment]
1)what is the ranking picture label?is the ranking level?like 1,2,3?represents the size of the croped picture?
Yes, the ranking label is exact the ranking level. 
2)in Fig3,when the N=1,what is the 11(N1)in the bule network lasts parts mean?the number of the ranking picture?or hat_Ci?
It's hat_Ci, which has length of minibatch size (N)
3) For each group of 5 ranked patches, it includes (4+3+2+1) number of different combinations of rankings, we always sample 5 groups in the minibatch, which ends up with   5 × (4 + 3 + 2 + 1) = 50 pairs.
Hope it helps.

**Comment by xwjBupt** [comment]
thanks for your reply!!so (4+3+2+1) means 4 patches of ranking 4  + 3 patches of ranking 3 + 2 patches of ranking 2 + 1 patches of ranking 1?

**Comment by xialeiliu** [comment]
Sorry, I am not so sure what you mean.

**Comment by xwjBupt** [comment]
不好意思，我英语不太好，我记得你应该是中国人吧，我用中文表述一下吧，就是一个group里面有4张rank为4的图片，3张rank为3的图片，然后以此类推？

**Comment by xialeiliu** [comment]
每个group有5个等级的图像块，例如第1等级的可以和其他四个等级的作比较，有4种可能，第2等级的也可以和其他四个等级的作比较，但是由于和1，2 和2，1 是一样的，所以去除这种可能就剩3种可能，目前为止是（4+3），然后以此类推。

**Comment by xwjBupt** [comment]
懂了！十分感谢你耐心的回答！！
